version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts/hello-dev.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./logs:/var/log/nginx
    depends_on:
      - php

  php:
    build: ./img/php
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ./www:/var/www

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: lego

